"""Scheduled wrappers that drive scanners against all active zones.

One function per scanner so APScheduler can stagger them. Each iterates every
active zone, calls the runner, returns aggregate counts.

The surface scanner is special — it uses the runner for the scan_run row
lifecycle but emits its findings through scanners.surface.probe_and_diff()
because the output shape (new-host alerts) doesn't fit RawFinding cleanly.
"""
from __future__ import annotations

import json
import logging
from datetime import datetime, timezone

from . import alerts, db
from .config import Settings
from .scanners import runner
from .scanners.base import ScanTarget
from .scanners.headers import HeadersScanner
from .scanners.nuclei import NucleiScanner
from .scanners.surface import probe_and_diff as surface_probe_and_diff
from .scanners.testssl import TestsslScanner
from .scanners.wpscan import WPScanScanner
from .scanners.zap import ZAPScanner

log = logging.getLogger(__name__)

SCANNER_IMPLS = {
    "nuclei":  NucleiScanner(),
    "wpscan":  WPScanScanner(),
    "testssl": TestsslScanner(),
    "headers": HeadersScanner(),
    "zap":     ZAPScanner(),
}


def _make_target(zone: dict) -> ScanTarget:
    return ScanTarget(
        zone_id=zone["id"],
        zone_name=zone["name"],
        base_url=f"https://{zone['name']}",
        cf_zone_id=zone.get("cf_zone_id"),
    )


def _scan_all_zones(settings: Settings, conn, scanner_name: str) -> dict:
    row = runner.get_scanner_row(conn, scanner_name)
    if not row:
        log.warning("Scanner %s not registered or disabled — skip", scanner_name)
        return {"zones": 0}
    impl = SCANNER_IMPLS.get(scanner_name)
    if impl is None:
        log.error("No scanner impl registered for %s", scanner_name)
        return {"zones": 0}
    zones = runner.get_active_zones(conn)
    total = {"zones": 0, "findings_new": 0, "findings_total": 0, "findings_resolved": 0}
    for z in zones:
        target = _make_target(z)
        try:
            r = runner.run_scan(
                conn, settings=settings, scanner_impl=impl,
                scanner_row=row, target=target,
            )
            total["zones"] += 1
            total["findings_total"] += r.get("total", 0)
            total["findings_new"] += r.get("new", 0)
            total["findings_resolved"] += r.get("resolved", 0)
        except Exception:
            log.exception("Scanner %s crashed on %s", scanner_name, z["name"])
    return total


# ───── public APScheduler entrypoints ─────


def run_nuclei(settings: Settings, conn) -> dict:
    return _scan_all_zones(settings, conn, "nuclei")


def run_wpscan(settings: Settings, conn) -> dict:
    return _scan_all_zones(settings, conn, "wpscan")


def run_testssl(settings: Settings, conn) -> dict:
    return _scan_all_zones(settings, conn, "testssl")


def run_headers(settings: Settings, conn) -> dict:
    return _scan_all_zones(settings, conn, "headers")


def run_zap(settings: Settings, conn) -> dict:
    return _scan_all_zones(settings, conn, "zap")


def run_surface(settings: Settings, conn) -> dict:
    """Attack-surface diff. Doesn't go through the standard runner because
    its output is host-discovery, not vulnerability findings."""
    row = runner.get_scanner_row(conn, "surface")
    if not row:
        log.warning("surface scanner not registered — skip")
        return {"zones": 0}
    zones = runner.get_active_zones(conn)
    total = {"zones": 0, "discovered": 0, "new": 0, "lost": 0}
    for z in zones:
        target = _make_target(z)
        # Manually manage the scan_runs row + emit a single "new-subdomain" finding
        # per newly-discovered host so it flows into the VAPT pipeline.
        with conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO mmwss.vapt_reports
                    (title, vendor, report_date, kind, scanner_id, notes)
                SELECT %s, 'MMWSS internal scan', %s, 'internal_scan', %s, %s
                WHERE NOT EXISTS (
                    SELECT 1 FROM mmwss.vapt_reports
                     WHERE kind = 'internal_scan' AND scanner_id = %s AND title = %s
                )
                RETURNING id
                """,
                (
                    f"Internal surface scan — {z['name']} — {datetime.now(timezone.utc).strftime('%Y-%m')}",
                    datetime.now(timezone.utc).date(), row["id"],
                    f"Auto-generated by collector for surface scanner against {z['name']}",
                    row["id"],
                    f"Internal surface scan — {z['name']} — {datetime.now(timezone.utc).strftime('%Y-%m')}",
                ),
            )
            r_row = cur.fetchone()
            if r_row:
                vapt_report_id = r_row["id"]
            else:
                cur.execute(
                    "SELECT id FROM mmwss.vapt_reports WHERE kind='internal_scan' "
                    "AND scanner_id=%s AND title=%s LIMIT 1",
                    (row["id"],
                     f"Internal surface scan — {z['name']} — {datetime.now(timezone.utc).strftime('%Y-%m')}"),
                )
                vapt_report_id = cur.fetchone()["id"]

            cur.execute(
                """
                INSERT INTO mmwss.scan_runs
                    (scanner_id, zone_id, vapt_report_id, target_url, status, triggered_by)
                VALUES (%s, %s, %s, %s, 'running', 'scheduled')
                RETURNING id
                """,
                (row["id"], z["id"], vapt_report_id, target.base_url),
            )
            run_id = cur.fetchone()["id"]
        conn.commit()

        result = {}
        try:
            result = surface_probe_and_diff(conn, target, row.get("config_json") or {})
            for host, meta in result.get("new_hosts", []):
                if host == target.zone_name:
                    continue   # apex doesn't count as "new"
                _emit_new_host_finding(
                    conn, target=target, host=host, meta=meta,
                    vapt_report_id=vapt_report_id, scan_run_id=run_id,
                )
            total["zones"] += 1
            total["discovered"] += result.get("discovered", 0)
            total["new"] += result.get("new", 0)
            total["lost"] += result.get("lost", 0)
            status = "ok"
            err = None
        except Exception as e:
            log.exception("surface scan failed for %s", z["name"])
            status = "failed"
            err = str(e)[:300]

        with conn.cursor() as cur:
            cur.execute(
                """
                UPDATE mmwss.scan_runs
                   SET status = %s,
                       finished_at = now(),
                       duration_secs = GREATEST(0, EXTRACT(EPOCH FROM (now() - started_at))::int),
                       error_message = %s,
                       findings_total = %s,
                       findings_new = %s
                 WHERE id = %s
                """,
                (status, err, result.get("discovered", 0), result.get("new", 0), run_id),
            )
            cur.execute("UPDATE mmwss.scanners SET last_run_at = now() WHERE id = %s", (row["id"],))
        conn.commit()
    return total


def _emit_new_host_finding(conn, *, target: ScanTarget, host: str, meta: dict,
                           vapt_report_id: int, scan_run_id: int) -> None:
    from .scanners.triage import fingerprint, compute_risk_score
    template_id = f"new-subdomain/{host}"
    fp = fingerprint("surface", template_id, host, None)
    # Skip if we've already emitted this one (shouldn't happen due to surface_hosts
    # check, but defense-in-depth)
    with conn.cursor() as cur:
        cur.execute("SELECT id FROM mmwss.vapt_findings WHERE fingerprint = %s", (fp,))
        if cur.fetchone():
            return
        status_text = f"Status: {meta.get('status') or 'unreachable'}"
        server_text = f"Server: {meta.get('server') or 'unknown'}"
        title_text = f"Title: {meta.get('title') or ''}".strip()
        sev = "low"     # new subdomains are informational by default; rules can escalate
        sla = 60 * 24 * 3600   # low → 60 days
        risk = compute_risk_score(severity=sev, cvss=None, epss=None, asset_multiplier=1.0)
        now = datetime.now(timezone.utc)
        cur.execute(
            """
            INSERT INTO mmwss.vapt_findings
                (report_id, vendor_finding_id, title, description, severity,
                 zone_id, sla_resolution_secs,
                 source, scanner, scanner_template_id, target_url, parameter,
                 fingerprint, raw_output_json, risk_score,
                 first_seen_at, last_seen_at, scan_run_id, status)
            VALUES (%s, NULL, %s, %s, %s,
                    %s, %s,
                    'internal_scan', 'surface', %s, %s, NULL,
                    %s, %s::jsonb, %s,
                    %s, %s, %s, 'open')
            """,
            (
                vapt_report_id,
                f"New subdomain discovered: {host}",
                "\n".join([
                    f"A new host was discovered for {target.zone_name}: {host}",
                    status_text, server_text, title_text,
                    "",
                    "Verify this is an intended deployment. If not, identify and remove or restrict access.",
                ]),
                sev, target.zone_id, sla,
                template_id, host,
                fp, json.dumps(meta), risk,
                now, now, scan_run_id,
            ),
        )
    conn.commit()
