"""Scanner orchestrator.

For a (scanner, zone) pair:
  1. Open a scan_runs row.
  2. Create / reuse the internal_scan vapt_reports row for this run.
  3. Invoke scanner.run(target).
  4. For each RawFinding: triage → upsert into vapt_findings (dedup by fingerprint).
  5. Stale-finding sweep: anything previously open from this scanner+target that
     wasn't re-seen in this run gets its consecutive_misses bumped; after the
     threshold the runner auto-marks it verified (the retest passed implicitly).
  6. Close the scan_runs row with counts.
  7. For genuinely-new (first_seen this run) findings of medium+, auto-create
     a ticket via the same mapping VAPT vendor findings use.
"""
from __future__ import annotations

import json
import logging
import os
import time
from datetime import datetime, timezone
from pathlib import Path

from .. import alerts
from . import remediation, triage
from .base import RawFinding, ScanTarget, Scanner

log = logging.getLogger(__name__)

# Severity → SLA (seconds) — matches mmwss_app.vapt.SLA_BY_SEVERITY
SLA_BY_SEVERITY = {
    "critical":  8 * 3600,
    "high":     14 * 24 * 3600,
    "medium":   30 * 24 * 3600,
    "low":      60 * 24 * 3600,
    "info":      0,
}

# Severity → ticket priority — mirrors mmwss_app.vapt.SEVERITY_TO_TICKET_PRIORITY
SEVERITY_TO_TICKET_PRIORITY = {
    "critical": "p1",
    "high":     "p2",
    "medium":   "p3",
    "low":      "p4",
}

# SLA targets per priority (response_secs, resolution_secs) — mirrors mmwss_app.sla.TARGETS
SLA_TARGETS = {
    "p1": (2 * 3600,        8 * 3600),
    "p2": (4 * 3600,       24 * 3600),
    "p3": (1 * 24 * 3600,  3 * 24 * 3600),
    "p4": (3 * 24 * 3600,  7 * 24 * 3600),
}

# After this many consecutive runs without re-detection, an open finding is
# auto-verified (assumed remediated). Conservative default: 2 misses for
# scanners that run weekly = 2 weeks of clean scans before we close it.
AUTO_VERIFY_MISSES = 2

ARTIFACT_DIR = Path(os.environ.get("MMWSS_SCAN_ARTIFACTS", "/app/reports/scans"))


def _ensure_internal_report(conn, scanner_row: dict, target: ScanTarget) -> int:
    """Internal-scan vapt_reports are bucketed per (scanner, zone, month)
    so they don't proliferate. One report row holds N scan runs' findings."""
    today = datetime.now(timezone.utc).strftime("%Y-%m")
    title = f"Internal {scanner_row['name']} scan — {target.zone_name} — {today}"
    with conn.cursor() as cur:
        cur.execute(
            """
            SELECT id FROM mmwss.vapt_reports
             WHERE kind = 'internal_scan'
               AND scanner_id = %s
               AND title = %s
             LIMIT 1
            """,
            (scanner_row["id"], title),
        )
        row = cur.fetchone()
        if row:
            return row["id"]
        cur.execute(
            """
            INSERT INTO mmwss.vapt_reports
                (title, vendor, report_date, kind, scanner_id, notes)
            VALUES (%s, %s, %s, 'internal_scan', %s, %s)
            RETURNING id
            """,
            (title, "MMWSS internal scan", datetime.now(timezone.utc).date(),
             scanner_row["id"],
             f"Auto-generated by collector for scanner '{scanner_row['name']}' against {target.base_url}"),
        )
        conn.commit()
        return cur.fetchone()["id"]


def _open_scan_run(conn, *, scanner_id: int, zone_id: int, vapt_report_id: int,
                   target_url: str, triggered_by: str,
                   triggered_by_user_id: int | None) -> int:
    with conn.cursor() as cur:
        cur.execute(
            """
            INSERT INTO mmwss.scan_runs
                (scanner_id, zone_id, vapt_report_id, target_url,
                 status, triggered_by, triggered_by_user_id)
            VALUES (%s, %s, %s, %s, 'running', %s, %s)
            RETURNING id
            """,
            (scanner_id, zone_id, vapt_report_id, target_url, triggered_by, triggered_by_user_id),
        )
        run_id = cur.fetchone()["id"]
    conn.commit()
    return run_id


def _close_scan_run(conn, run_id: int, *, status: str, error: str | None,
                    artifact_path: str | None,
                    totals: dict[str, int]) -> None:
    with conn.cursor() as cur:
        cur.execute(
            """
            UPDATE mmwss.scan_runs
               SET status = %s,
                   finished_at = now(),
                   duration_secs = GREATEST(0, EXTRACT(EPOCH FROM (now() - started_at))::int),
                   error_message = %s,
                   raw_artifact_path = %s,
                   findings_total = %s,
                   findings_new = %s,
                   findings_resolved = %s,
                   findings_suppressed = %s
             WHERE id = %s
            """,
            (status, error, artifact_path,
             totals.get("total", 0), totals.get("new", 0),
             totals.get("resolved", 0), totals.get("suppressed", 0), run_id),
        )
    conn.commit()


def _persist_finding(
    conn,
    *,
    finding: RawFinding,
    scanner_name: str,
    decision: triage.TriageDecision,
    target: ScanTarget,
    vapt_report_id: int,
    scan_run_id: int,
) -> tuple[int, bool]:
    """Upsert by fingerprint. Returns (finding_id, is_new)."""
    fp = triage.fingerprint(scanner_name, finding.template_id, finding.target_url, finding.parameter)
    now = datetime.now(timezone.utc)
    sla = SLA_BY_SEVERITY.get(decision.final_severity, SLA_BY_SEVERITY["medium"])
    remediation_text = remediation.lookup(scanner_name, finding.template_id, decision.final_severity)

    # Build proof_text including rule notes
    proof_parts: list[str] = []
    if finding.proof:
        proof_parts.append(finding.proof)
    if decision.extra_notes:
        proof_parts.append("\n— Triage notes —\n" + "\n".join(decision.extra_notes))
    proof_text = "\n\n".join(proof_parts) if proof_parts else None

    description_full = (finding.description or "") + "\n\n— Remediation —\n" + remediation_text

    with conn.cursor() as cur:
        # Lookup existing
        cur.execute(
            "SELECT id, status, severity, first_seen_at FROM mmwss.vapt_findings WHERE fingerprint = %s",
            (fp,),
        )
        existing = cur.fetchone()

        if existing:
            # Re-detection: bump last_seen, reset miss counter; if engineer had it as
            # remediated/verified but it's now flagged again, re-open.
            new_status = existing["status"]
            if existing["status"] in ("remediated", "verified") and decision.initial_status == "open":
                new_status = "open"   # regression
            cur.execute(
                """
                UPDATE mmwss.vapt_findings
                   SET last_seen_at = %s,
                       consecutive_misses = 0,
                       scan_run_id = %s,
                       status = %s,
                       risk_score = %s
                 WHERE id = %s
                 RETURNING id
                """,
                (now, scan_run_id, new_status, decision.risk_score, existing["id"]),
            )
            conn.commit()
            return existing["id"], False

        # Insert new finding
        cur.execute(
            """
            INSERT INTO mmwss.vapt_findings
                (report_id, vendor_finding_id, title, description, severity,
                 cve_reference, cvss_score, owasp_category, affected_url, proof_text,
                 zone_id, sla_resolution_secs,
                 source, scanner, scanner_template_id, target_url, parameter,
                 fingerprint, raw_output_json, epss_score, risk_score,
                 first_seen_at, last_seen_at, scan_run_id, status, suppressed_by_rule_id)
            VALUES (%s, NULL, %s, %s, %s, %s, %s, %s, %s, %s,
                    %s, %s,
                    'internal_scan', %s, %s, %s, %s,
                    %s, %s::jsonb, %s, %s,
                    %s, %s, %s, %s, %s)
            RETURNING id
            """,
            (vapt_report_id, finding.title, description_full, decision.final_severity,
             finding.cve, finding.cvss, finding.owasp_category, finding.target_url, proof_text,
             target.zone_id, sla,
             scanner_name, finding.template_id, finding.target_url, finding.parameter,
             fp, json.dumps(finding.raw) if finding.raw else None,
             finding.epss, decision.risk_score,
             now, now, scan_run_id, decision.initial_status, decision.suppressed_rule_id),
        )
        new_id = cur.fetchone()["id"]
    conn.commit()
    return new_id, True


def _auto_create_ticket(conn, *, finding_id: int, finding: RawFinding,
                        decision: triage.TriageDecision, target: ScanTarget,
                        scanner_name: str) -> int | None:
    """Same logic as mmwss_app.vapt.create_finding's auto-ticket block."""
    if decision.initial_status != "open":
        return None
    priority = SEVERITY_TO_TICKET_PRIORITY.get(decision.final_severity)
    if not priority:
        return None    # 'info' has no ticket
    resp_s, resol_s = SLA_TARGETS[priority]
    tag = f"[{decision.final_severity.upper()}]"
    ttitle = f"{tag} Scanner({scanner_name}): {finding.title}".strip()[:200]
    cve_ref = f"\nCVE: {finding.cve}" if finding.cve else ""
    cvss_ref = f"\nCVSS: {finding.cvss}" if finding.cvss else ""
    risk_ref = f"\nRisk score: {decision.risk_score}"
    tdesc = (
        f"{finding.description or ''}{cve_ref}{cvss_ref}{risk_ref}\n"
        f"Scanner: {scanner_name}\nTemplate: {finding.template_id}\nTarget: {finding.target_url}"
    ).strip()
    with conn.cursor() as cur:
        cur.execute(
            """
            INSERT INTO mmwss.tickets
                (title, description, priority, category, source, zone_id,
                 sla_response_secs, sla_resolution_secs)
            VALUES (%s, %s, %s, 'vapt', 'auto_alert', %s, %s, %s)
            RETURNING id
            """,
            (ttitle, tdesc, priority, target.zone_id, resp_s, resol_s),
        )
        ticket_id = cur.fetchone()["id"]
        cur.execute(
            "INSERT INTO mmwss.ticket_events (ticket_id, event_type, details_json) "
            "VALUES (%s, 'created', %s::jsonb)",
            (ticket_id,
             json.dumps({"source": "scanner_finding", "finding_id": finding_id,
                         "scanner": scanner_name, "severity": decision.final_severity})),
        )
        cur.execute(
            "UPDATE mmwss.vapt_findings SET ticket_id = %s WHERE id = %s",
            (ticket_id, finding_id),
        )
    conn.commit()
    return ticket_id


def _sweep_stale(conn, *, scanner_name: str, zone_id: int, scan_run_id: int) -> int:
    """Findings from this scanner+zone that weren't re-seen in this run get
    consecutive_misses bumped. Once threshold is hit and they're still 'open' or
    'in_progress', auto-mark as 'verified' (the retest passed implicitly).
    Returns number of findings auto-verified by this run."""
    auto_verified = 0
    with conn.cursor() as cur:
        # Bump miss counter on stale findings (still tracked but not in this run)
        cur.execute(
            """
            UPDATE mmwss.vapt_findings
               SET consecutive_misses = consecutive_misses + 1
             WHERE source = 'internal_scan'
               AND scanner = %s
               AND zone_id = %s
               AND status IN ('open', 'in_progress', 'remediated')
               AND (scan_run_id IS NULL OR scan_run_id != %s)
               AND id NOT IN (
                   SELECT id FROM mmwss.vapt_findings
                    WHERE scan_run_id = %s
               )
            """,
            (scanner_name, zone_id, scan_run_id, scan_run_id),
        )
        # Auto-verify those past threshold
        cur.execute(
            """
            UPDATE mmwss.vapt_findings
               SET status = 'verified',
                   remediated_at = COALESCE(remediated_at, now()),
                   verified_at   = now()
             WHERE source = 'internal_scan'
               AND scanner = %s
               AND zone_id = %s
               AND status IN ('open', 'in_progress', 'remediated')
               AND consecutive_misses >= %s
             RETURNING id, ticket_id
            """,
            (scanner_name, zone_id, AUTO_VERIFY_MISSES),
        )
        verified = cur.fetchall()
        for v in verified:
            auto_verified += 1
            if v.get("ticket_id"):
                # Auto-resolve the linked ticket too
                cur.execute(
                    """
                    UPDATE mmwss.tickets
                       SET status = 'resolved',
                           resolved_at = COALESCE(resolved_at, now()),
                           response_at = COALESCE(response_at, opened_at),
                           resolution_notes = COALESCE(resolution_notes,
                              'Auto-resolved: finding no longer detected by scanner after ' ||
                              %s::text || ' consecutive clean scans.')
                     WHERE id = %s AND status IN ('open', 'in_progress')
                    """,
                    (AUTO_VERIFY_MISSES, v["ticket_id"]),
                )
                cur.execute(
                    "INSERT INTO mmwss.ticket_events (ticket_id, event_type, details_json) "
                    "VALUES (%s, 'resolved', %s::jsonb)",
                    (v["ticket_id"],
                     json.dumps({"source": "scanner_auto_verify",
                                 "finding_id": v["id"], "misses": AUTO_VERIFY_MISSES})),
                )
    conn.commit()
    return auto_verified


def _save_artifact(scan_run_id: int, raw_text: str) -> str | None:
    """Persist raw scanner output for audit. Returns the saved path."""
    try:
        ARTIFACT_DIR.mkdir(parents=True, exist_ok=True)
        path = ARTIFACT_DIR / f"run-{scan_run_id}.txt"
        path.write_text(raw_text or "", encoding="utf-8")
        return str(path)
    except Exception:
        log.exception("Failed to save artifact for run %d", scan_run_id)
        return None


def run_scan(
    conn,
    *,
    settings,
    scanner_impl: Scanner,
    scanner_row: dict,
    target: ScanTarget,
    triggered_by: str = "scheduled",
    triggered_by_user_id: int | None = None,
) -> dict:
    """Execute one scanner against one zone. Returns a summary dict."""
    vapt_report_id = _ensure_internal_report(conn, scanner_row, target)
    run_id = _open_scan_run(
        conn,
        scanner_id=scanner_row["id"], zone_id=target.zone_id,
        vapt_report_id=vapt_report_id, target_url=target.base_url,
        triggered_by=triggered_by, triggered_by_user_id=triggered_by_user_id,
    )

    artifact_text_parts: list[str] = []
    status = "ok"
    error: str | None = None
    counts = {"total": 0, "new": 0, "resolved": 0, "suppressed": 0}

    try:
        rules = triage.load_active_rules(conn)
        asset_mult = triage.get_asset_multiplier(conn, target.zone_id)
        config = scanner_row.get("config_json") or {}
        t0 = time.monotonic()
        log.info("scan start scanner=%s zone=%s run=%d", scanner_impl.name, target.zone_name, run_id)
        raw_findings = scanner_impl.run(target, config)
        log.info("scan done  scanner=%s zone=%s run=%d findings=%d in %.1fs",
                 scanner_impl.name, target.zone_name, run_id, len(raw_findings), time.monotonic() - t0)

        for rf in raw_findings:
            try:
                artifact_text_parts.append(json.dumps({
                    "template_id": rf.template_id, "severity": rf.severity,
                    "target_url": rf.target_url, "parameter": rf.parameter,
                    "title": rf.title, "cve": rf.cve, "cvss": rf.cvss,
                }, ensure_ascii=False))
                decision = triage.triage(
                    rf, scanner_name=scanner_impl.name,
                    zone_id=target.zone_id, asset_multiplier=asset_mult, rules=rules,
                )
                if decision.suppressed_rule_id is not None:
                    counts["suppressed"] += 1
                fid, is_new = _persist_finding(
                    conn, finding=rf, scanner_name=scanner_impl.name,
                    decision=decision, target=target,
                    vapt_report_id=vapt_report_id, scan_run_id=run_id,
                )
                counts["total"] += 1
                if is_new:
                    counts["new"] += 1
                    if decision.initial_status == "open":
                        tid = _auto_create_ticket(
                            conn, finding_id=fid, finding=rf,
                            decision=decision, target=target,
                            scanner_name=scanner_impl.name,
                        )
                        if tid:
                            log.info("auto-ticket #%d for new finding #%d (sev=%s)",
                                     tid, fid, decision.final_severity)
                            try:
                                alerts.notify_scanner_finding(
                                    settings, conn,
                                    zone_id=target.zone_id,
                                    zone_name=target.zone_name,
                                    finding_id=fid,
                                    ticket_id=tid,
                                    severity=decision.final_severity,
                                    title=rf.title,
                                    scanner=scanner_impl.name,
                                )
                            except Exception:
                                pass    # alerts best-effort
            except Exception:
                log.exception("Failed to persist finding template=%s url=%s",
                              rf.template_id, rf.target_url)

        counts["resolved"] = _sweep_stale(
            conn, scanner_name=scanner_impl.name,
            zone_id=target.zone_id, scan_run_id=run_id,
        )
    except Exception as e:
        status = "failed"
        error = str(e)[:500]
        log.exception("Scanner %s crashed on zone %s", scanner_impl.name, target.zone_name)
    finally:
        artifact_path = _save_artifact(run_id, "\n".join(artifact_text_parts))
        _close_scan_run(conn, run_id, status=status, error=error,
                        artifact_path=artifact_path, totals=counts)
        with conn.cursor() as cur:
            cur.execute(
                "UPDATE mmwss.scanners SET last_run_at = now() WHERE id = %s",
                (scanner_row["id"],),
            )
        conn.commit()

    return {"run_id": run_id, "status": status, **counts}


def get_active_zones(conn) -> list[dict]:
    with conn.cursor() as cur:
        cur.execute(
            "SELECT id, name FROM mmwss.zones WHERE status = 'active' ORDER BY name"
        )
        return cur.fetchall()


def get_scanner_row(conn, name: str) -> dict | None:
    with conn.cursor() as cur:
        cur.execute("SELECT * FROM mmwss.scanners WHERE name = %s AND enabled = TRUE", (name,))
        return cur.fetchone()
